### PR TITLE
Fix WebAPI issues

### LINKED ISSUE #425: WebAPI issueses
### Version used

* `AET 3.0.1`

### Context of the issue/feature

While creating AETs API test I've spotted several API related bugs:
1) Get artifact by artifact Id for **wrong** artifactId returns code 500 instead of 400
request: GET: `http://aet-vagrant:8181/api/artifact?company=aet&project=aet&id=99999999`
response: `HTTP ERROR 500`
expected reposne: 400 with proper error message
2) Get metadata api for **wrong** correlationId returns error message text which doesn't describe the problem:
request: GET: `http://aet-vagrant:8181/api/metadata?company=aet&project=aet&correlationId=99999999`
response:`{
"message": "Unable to get Suite Metadata for {company='aet', project='aet'}"
}`
3) Get metadata api for **wrong** suite name returns error message skipping suite name:
request: GET: `http://aet-vagrant:8181/api/metadata?company=aet&project=aet&suite=no_existing_suite`
response:`{
"message": "Unable to get Suite Metadata for {company='aet', project='aet'}"
}`
expected reposne: `{
"message": "Unable to get Suite Metadata for no_existing_suite {company='aet', project='aet'}"
}`
4) Get metadata by suite name and version for **wrong** suite version returns error message text which doesn't describe the problem:
request: GET: `http://aet-vagrant:8181/api/metadata?company=aet&project=aet&suite=main&version=999`
response:`{
"message": "Unable to get Suite Metadata for {company='aet', project='aet'}"
}`
5) Get correlationIds and versions by suite name for **not existing** suite returns wrong status code (404 instead of 400) with **proper error message:**
request: GET: `http://aet-vagrant:8181/api/history?company=aet&project=aet&suite=no_existing_suite`
response: 404`{"message":"History not found for suite: no_existing_suite {company\u003d\u0027aet\u0027, project\u003d\u0027aet\u0027}"}`
6) Get all locked suites returns JSON object with looks like not valid json object:
request: GET: `http://aet-vagrant:8181/configs/locks`
response:`{aet-aet-main2=aet-aet-main2-1540988624814, aet-aet-main=aet-aet-main-1540540651320}`

Documentation link: https://github.com/Cognifide/aet/wiki/WebAPI

### PR DESCRIPTION
**Pull request by wblachowski**
I fixed some inconsistencies in WebAPI responses and provided more meaningful 404 messages.

Closes #425 

## Description
Issues addressed:
1.  Get artifact by artifactId for wrong artifactId:
http://aet-vagrant:8181/api/artifact?company=company&project=project&id=99999999
- Old response:
`500`
- New response:
    `404`
    ```javascript
    {
    "message": "Unable to get artifact with id: 99999999 for {company='company', project='project'}"
    }
    ```

2. Get metadata for wrong correlationId
http://aet-vagrant:8181/api/artifact?company=company&project=project&id=99999999
- Old response:
     `400`
     ```javascript
    {
    "message": "Unable to get Suite Metadata for {company='company', project='project'}"
    {
    ```
- New response:
    `404`
    ```javascript
    {
    "message": "Unable to get Suite Metadata with correlationId: 99999999 for {company='company', project='project'}"
    }
    ```

3. Get metadata for wrong suite name
http://aet-vagrant:8181/api/metadata?company=company&project=project&suite=no_existing_suite
- Old response:
     `400`
     ```javascript
    {
    "message": "Unable to get Suite Metadata for {company='company', project='project'}"
    }
    ```
- New response:
    `404`
     ```javascript
     {
     "message": "Unable to get Suite Metadata with suite name: no_existing_suite for {company='company', project='project'}"
     }
    ```

4. Get metadata by suite name and wrong version
http://aet-vagrant:8181/api/metadata?company=company&project=project&suite=test-suite&version=999
- Old response:
     `400`
     ```javascript
     {
     "message": "Unable to get Suite Metadata for {company='company', project='project'}"
     }
    ```
- New response:
     `404`
     ```javascript
     {
     "message": "Unable to get Suite Metadata with suite name: test-suite, version: 999 for {company='company', project='project'}"
     }
    ```

6. Get locked suites
http://aet-vagrant:8181/configs/locks
- Old response:
     ```javascript
     {
     company-project-test-suite=company-project-test-suite-1548143700186, 
     secondcompany-secondproject-test-suite2=secondcompany-secondproject-test-suite2-1548143698893
     }
    ```
- New response:
     ```javascript
     {
     "company-project-test-suite": "company-project-test-suite-1548141903906",
     "secondcompany-secondproject-test-suite2": "secondcompany-secondproject-test-suite2-1548141899754"
     }
    ```

## Motivation and Context
Closes #425 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the [code style](/CONTRIBUTING.md#coding-conventions) of this project.
- [x] I have reviewed (and updated if needed) the documentation regarding this change

---
I hereby agree to the terms of the AET Contributor License Agreement.

### CODE REVIEW

File: rest-endpoint/src/main/java/com/cognifide/aet/rest/MetadataServlet.java [hunk 1]
```diff
@@ -192,6 +190,21 @@ private void checkLock(String suiteIdentifier) throws AETException {
...
 
+  private void createNotFoundResponse(HttpServletResponse response, String correlationId, String suiteName, String suiteVersion, DBKey dbKey) throws IOException {
+    response.setStatus(HttpURLConnection.HTTP_NOT_FOUND);
+    String paramsValuesMessage = "";
+    if (correlationId != null) {
+      paramsValuesMessage = String.format("correlationId: %s", correlationId);
+    } else if (suiteName != null) {
+      paramsValuesMessage = String.format("suite name: %s", suiteName);
+      if (suiteVersion != null) {
+        paramsValuesMessage = String.format("%s, version: %s", paramsValuesMessage, suiteVersion);
```
Comment (plutasnyy) [inline rest-endpoint/src/main/java/com/cognifide/aet/rest/MetadataServlet.java]: Is everything ok with formatting?

Comment (wblachowski) [reply rest-endpoint/src/main/java/com/cognifide/aet/rest/MetadataServlet.java]: Looks fine to me, these are nested if statements. It's OK according to Google Style

**Comment by bambroziak** [comment]
Tested and accepted.
I've rebuilded Integration with changes and checked responses - all of them were new ones.

QA Covered.
